# Generated by Django 6.0.2 on 2026-02-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('task', 'Task Assignment'), ('group', 'Group Update'), ('system', 'System Notification'), ('pomodoro_start', 'Pomodoro Started'), ('focus_end', 'Focus Session Ended'), ('break_start', 'Break Started'), ('break_end', 'Break Ended'), ('cycle_complete', 'Pomodoro Cycle Complete')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
