# Generated by Django 6.0 on 2026-02-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('task', 'Task Assignment'), ('group', 'Group Update'), ('system', 'System Notification'), ('pomodoro_start', 'Pomodoro Started'), ('focus_end', 'Focus Session Ended'), ('break_start', 'Break Started'), ('break_end', 'Break Ended'), ('cycle_complete', 'Pomodoro Cycle Complete')], max_length=20),
        ),
    ]
