# Generated by Django 6.0 on 2025-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/messages/'),
        ),
    ]
