# Generated by Django 6.0.2 on 2026-02-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_studygroup_invitation_token'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='subject',
        ),
        migrations.AddField(
            model_name='studysession',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='group.studygroup'),
        ),
    ]
