apiVersion: v1
kind: ConfigMap
metadata:
  name: studybuddy-config
  namespace: studybuddy
  labels:
    app.kubernetes.io/name: studybuddy
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "studybuddy"
  DB_USER: "studybuddy"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  FRONTEND_URL: "http://studybuddy.local"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
