# Generated by Django 6.0.2 on 2026-02-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
