# Generated by Django 6.0 on 2025-12-05 07:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studygroup',
            unique_together={('group_name', 'created_by')},
        ),
    ]
