# Generated by Django 6.0 on 2025-12-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_studygroup_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
