# Generated by Django 5.2.7 on 2026-04-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_studygroup_invitation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='role',
        ),
    ]
