# Generated by Django 6.0 on 2025-12-05 08:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_studygroup_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
