# Generated by Django 6.0 on 2026-01-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_studygroup_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_description',
            field=models.TextField(blank=True, help_text='Optional description of the group'),
        ),
    ]
