# Generated by Django 6.0 on 2026-01-26 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0004_alter_studygroup_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.IntegerField(default=1500)),
                ('break_duration', models.IntegerField(default=300)),
                ('long_break_duration', models.IntegerField(default=900)),
                ('sessions_before_long_break', models.IntegerField(default=4)),
                ('remaining_seconds', models.IntegerField(default=1500)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('break', 'Break'), ('completed', 'Completed')], default='idle', max_length=20)),
                ('current_session_number', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to='group.studygroup')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pomodoro_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
