# Generated by Django 6.0.2 on 2026-02-05 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.IntegerField(default=1500)),
                ('break_duration', models.IntegerField(default=300)),
                ('long_break_duration', models.IntegerField(default=900)),
                ('sessions_before_long_break', models.IntegerField(default=4)),
                ('allow_member_pause', models.BooleanField(default=False)),
                ('sync_mode', models.CharField(choices=[('forced', 'Forced (All Members)'), ('flexible', 'Flexible (Invite Only)')], default='flexible', max_length=20)),
                ('phase', models.CharField(choices=[('work', 'Work'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], default='work', max_length=20)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='idle', max_length=20)),
                ('phase_start', models.DateTimeField(blank=True, null=True)),
                ('phase_duration', models.IntegerField(default=1500)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_seconds_at_pause', models.IntegerField(blank=True, null=True)),
                ('current_session_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to='group.studygroup')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pomodoro_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('work', 'Work'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], default='work', max_length=20)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='idle', max_length=20)),
                ('phase_start', models.DateTimeField(blank=True, null=True)),
                ('phase_duration', models.IntegerField(default=1500)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_seconds_at_pause', models.IntegerField(blank=True, null=True)),
                ('current_session_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pomodoro_sessions', to='group.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_pomodoro_sessions',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
