# Generated by Django 6.0 on 2026-01-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodorosession',
            old_name='started_at',
            new_name='paused_at',
        ),
        migrations.RenameField(
            model_name='pomodorosession',
            old_name='remaining_seconds',
            new_name='phase_duration',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='phase',
            field=models.CharField(choices=[('work', 'Work'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], default='work', max_length=20),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='phase_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='remaining_seconds_at_pause',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='idle', max_length=20),
        ),
    ]
