# Generated by Django 6.0 on 2026-01-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_rename_started_at_pomodorosession_paused_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='allow_member_pause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='sync_mode',
            field=models.CharField(choices=[('forced', 'Forced (All Members)'), ('flexible', 'Flexible (Invite Only)')], default='forced', max_length=20),
        ),
    ]
