# Generated by manual process for UserPomodoroSession model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0005_alter_studygroup_group_description'),
        ('pomodoro', '0003_pomodorosession_allow_member_pause_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('work', 'Work'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], default='work', max_length=20)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='idle', max_length=20)),
                ('phase_start', models.DateTimeField(blank=True, null=True)),
                ('phase_duration', models.IntegerField(default=1500)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_seconds_at_pause', models.IntegerField(blank=True, null=True)),
                ('current_session_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pomodoro_sessions', to='group.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_pomodoro_sessions',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
