# Generated by Django 6.0 on 2026-02-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0004_userpomodorosession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosession',
            name='sync_mode',
            field=models.CharField(choices=[('forced', 'Forced (All Members)'), ('flexible', 'Flexible (Invite Only)')], default='flexible', max_length=20),
        ),
    ]
