# Generated by Django 6.0.2 on 2026-02-23 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_studygroup_invitation_token'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyfile',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='studyfile',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='studyfile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='group.studygroup'),
        ),
        migrations.AddIndex(
            model_name='studyfile',
            index=models.Index(fields=['group'], name='study_files_group_i_19ef15_idx'),
        ),
        migrations.AddIndex(
            model_name='studyfile',
            index=models.Index(fields=['uploaded_at'], name='study_files_uploade_1a8247_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyfile',
            constraint=models.UniqueConstraint(fields=('group', 'filename'), name='unique_filename_per_group'),
        ),
    ]
