# Generated by Django 6.0.2 on 2026-02-10 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studytracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyactivity',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Study Activities'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-awarded_at']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon_name',
            field=models.CharField(default='default_badge', max_length=100),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='required_days',
            field=models.PositiveIntegerField(help_text='Days needed to unlock this badge'),
        ),
        migrations.AlterField(
            model_name='studyactivity',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studyactivity',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Time spent studying in minutes'),
        ),
        migrations.AlterField(
            model_name='studyactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studystreak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
